#!/bin/sh

# grep last 10 lines and LOGGREP syntax from LOGFILE to APPPATH
#
APPPATH="/path/to/php/folder"
LOGFILE="error log file"
LOGGREP="error"


tail -n 10 /var/log/$LOGFILE | grep -E $LOGGREP > $APPPATH/tmp.log

